
%TESTGUI Summary of this function goes here
%   Detailed explanation goes here

function [] = testGui()
S.fh = figure('units','pixels',...
              'position',[500 200 500 400],...
              'menubar','none',...
              'name','gui',...
              'numbertitle','off',...
              'resize','off');
S.pb = uicontrol('style','push',...
                 'units','pix',...
                 'position',[10 10 180 40],...
                 'fontsize',14,...
                 'string','Hi!');   
S.pb2 = uicontrol('style','push',...
                 'units','pix',...
                 'position',[50 50 180 80],...
                 'fontsize',14,...
                 'string','Hi2!');   
S.tx = uicontrol('style','text',...
                 'units','pix',...
                 'position',[10 55 180 40],...
                 'string','goodbye',...
                 'fontsize',23);
set(S.pb,'callback'   ,{@pb_call,S})
% Check if 'p' is pressed when focus on button and exec callback
set(S.pb,'KeyPressFcn',{@pb_kpf ,S});
% Check if 'p' is pressed when focus on figure and exec callback
set(S.fh,'KeyPressFcn',{@pb_kpf ,S});

% Callback for pushbutton, prints Hi! in cmd window
function pb_call(varargin)
S = varargin{3};  % Get the structure.
set(S.tx,'String', get(S.pb,'String'))
% Do same action as button when pressed 'p'

function pb_kpf(varargin)
varargin{1,2}.Character
if varargin{1,2}.Character == 'p'
    pb_call(varargin{:})
end




